FROM rust:1.81

WORKDIR /app

RUN git clone https://github.com/akhercha/gomu-gomu-no-gatling.git .

RUN git checkout fix/for_madara

RUN cargo build --release

COPY config/devnet.madara.yaml ./config/devnet.madara.yaml

CMD ["cargo", "run", "--release", "--", "shoot", "-c", "config/devnet.madara.yaml"]
